import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "@/styles/globals.css";
import 'react-toastify/ReactToastify.css';
import 'react-phone-number-input/style.css';
import ContextProvider from "@/providers/ContextProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
